name: Update DAGs

on:
  push:
    branches:
      - main

jobs:
  update-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync DAGs to Airflow server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.dopany-airflow.ddns.net }}
          username: ${{ secrets.airflow }}
          password: ${{ secrets.airflow }}
          source: "./dags/*"
          target: "/path/to/airflow/dags"

      - name: Restart Airflow Scheduler
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.dopany-airflow.ddns.net }}
          username: ${{ secrets.airflow }}
          password: ${{ secrets.airflow }}
          script: |
            airflow dags reload
