name: Update DAGs

on:
  push:
    branches:
      - main

jobs:
  update-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known_hosts
        run: |
          ssh-keyscan -p 2222 dopany-airflow.ddns.net >> ~/.ssh/known_hosts

      - name: Verify SSH Configuration
          run: |
            echo "SSH Configuration:"
            cat ~/.ssh/config || echo "No custom SSH config found"
            echo "Known Hosts:"
            cat ~/.ssh/known_hosts

      - name: Debug SSH Agent
        run: |
          ssh-add -l

      - name: Debug SSH Connection
        run: |
          ssh -vvv -p 2222 airflow@dopany-airflow.ddns.net "echo SSH connection successful"
      

      - name: Sync DAGs to Airflow server
        run: scp -r -P 2222 ./dags/* airflow@dopany-airflow.ddns.net:/opt/airflow/dags

      - name: Restart Airflow Scheduler
        uses: appleboy/ssh-action@master
        with:
          host: dopany-airflow.ddns.net
          username: airflow
          port: 2222
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            airflow dags reload